### ISSUE TITLE
V2ex 链接错误

### ISSUE THREAD

**Issue by Yawenina** [ttop5/to-be-slack#3]
V 站的链接错了，多了一个 `/` ， 导致页面 404
eg： https://www.v2ex.com//t/589400#reply97

![image](https://user-images.githubusercontent.com/13173126/62520243-bf283d00-b85f-11e9-8bd3-897187a32481.png)

**Comment by ttop5** [comment]
@Yawenina 感谢反馈，我会尽快修复哈。不过奇怪的是，我能打开诶233
![屏幕快照 2019-08-06 15 57 25](https://user-images.githubusercontent.com/9512362/62521890-1b409080-b863-11e9-9da6-7c3e6b59898d.png)

**Comment by Yawenina** [comment]
嗯是的，后面我也能打开了🐶

**Comment by timeromantic** [comment]
谢谢告知，稍后处理一下，不过双斜杠我这边能打开。



---原始邮件---
发件人: "Yawenina"<notifications@github.com>
发送时间: 2019年8月6日(星期二) 下午4:00
收件人: "ttop5/to-be-slack"<to-be-slack@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [ttop5/to-be-slack] V2ex 链接错误 (#3)



嗯是的，后面我也能打开了🐶

**Comment by ttop5** [comment]
已修正
