### ISSUE TITLE
网站接口挂掉了，所有内容不显示

### ISSUE THREAD

**Issue by wubuzhi** [ttop5/to-be-slack#45]
请开发这个网站的码农，今晚加班把它修改好

**Comment by ttop5** [comment]
你是哪来的傻逼，给了多少钱还是咋的，在这叽叽歪歪的

**Comment by wubuzhi** [comment]
> 你是哪来的傻逼，给了多少钱还是咋的，在这叽叽歪歪的

你他妈才是傻逼呢，网站挂了不修复，看你妈的动画，狗子

**Comment by ttop5** [comment]
@wubuzhi  为啥要给你这种傻逼用，除了做个伸手巨婴和bb还会点啥，自己写去啊nt玩意！
